MODULES = {
    "admissions": {
        "table": "admissions",
        "title": "Admissions",
        "permission": "admissions.manage",
        "search": ["application_no", "first_name", "last_name", "guardian_phone"],
        "list": ["application_no", "first_name", "last_name", "grade_applied", "status", "created_at"],
        "fields": {
            "application_no": {"type": "text", "required": True},
            "first_name": {"type": "text", "required": True},
            "last_name": {"type": "text", "required": True},
            "date_of_birth": {"type": "date", "required": True},
            "gender": {"type": "select", "required": True, "options": ["Female", "Male", "Other"]},
            "grade_applied": {"type": "text", "required": True},
            "guardian_name": {"type": "text", "required": True},
            "guardian_phone": {"type": "tel", "required": True},
            "guardian_email": {"type": "email"},
            "status": {"type": "select", "required": True, "options": ["Draft", "Payment Pending", "Submitted", "Reviewed", "Under Review", "Documents Verified", "Accepted", "Admitted", "Rejected", "Enrolled"]},
            "notes": {"type": "textarea"},
        },
    },
    "students": {
        "table": "students",
        "title": "Students",
        "permission": "students.manage",
        "search": ["admission_no", "first_name", "last_name", "email", "phone"],
        "list": ["admission_no", "first_name", "last_name", "class_name", "status", "created_at"],
        "joins": "LEFT JOIN classes c ON c.id = students.class_id",
        "select_extra": ["c.name AS class_name"],
        "fields": {
            "admission_no": {"type": "text", "required": True},
            "first_name": {"type": "text", "required": True},
            "last_name": {"type": "text", "required": True},
            "date_of_birth": {"type": "date", "required": True},
            "gender": {"type": "select", "required": True, "options": ["Female", "Male", "Other"]},
            "class_id": {"type": "number", "label": "Class ID"},
            "email": {"type": "email"},
            "phone": {"type": "tel"},
            "address": {"type": "textarea"},
            "status": {"type": "select", "required": True, "options": ["Active", "Inactive", "Graduated", "Transferred"]},
        },
    },
    "parents": {
        "table": "parents",
        "title": "Parents",
        "permission": "parents.manage",
        "search": ["first_name", "last_name", "email", "phone", "occupation"],
        "list": ["first_name", "last_name", "relationship", "phone", "email", "created_at"],
        "fields": {
            "student_id": {"type": "number", "required": True, "label": "Student ID"},
            "first_name": {"type": "text", "required": True},
            "last_name": {"type": "text", "required": True},
            "relationship": {"type": "select", "required": True, "options": ["Mother", "Father", "Guardian", "Sponsor"]},
            "phone": {"type": "tel", "required": True},
            "email": {"type": "email"},
            "occupation": {"type": "text"},
            "address": {"type": "textarea"},
        },
    },
    "teachers": {
        "table": "teachers",
        "title": "Teachers",
        "permission": "teachers.manage",
        "search": ["employee_no", "first_name", "last_name", "email", "department"],
        "list": ["employee_no", "first_name", "last_name", "department", "status", "created_at"],
        "fields": {
            "employee_no": {"type": "text", "required": True},
            "first_name": {"type": "text", "required": True},
            "last_name": {"type": "text", "required": True},
            "email": {"type": "email", "required": True},
            "phone": {"type": "tel"},
            "department": {"type": "text"},
            "qualification": {"type": "text"},
            "hire_date": {"type": "date"},
            "status": {"type": "select", "required": True, "options": ["Active", "On Leave", "Inactive"]},
        },
    },
    "academic": {
        "table": "academic_years",
        "title": "Academic Years",
        "permission": "academic.manage",
        "search": ["name", "status"],
        "list": ["name", "starts_on", "ends_on", "status", "created_at"],
        "fields": {
            "name": {"type": "text", "required": True},
            "starts_on": {"type": "date", "required": True},
            "ends_on": {"type": "date", "required": True},
            "status": {"type": "select", "required": True, "options": ["Planning", "Current", "Closed"]},
        },
    },
    "classes": {
        "table": "classes",
        "title": "Classes",
        "permission": "academic.manage",
        "search": ["name", "grade_level", "room"],
        "list": ["name", "grade_level", "room", "capacity", "created_at"],
        "fields": {
            "name": {"type": "text", "required": True},
            "grade_level": {"type": "text", "required": True},
            "room": {"type": "text"},
            "capacity": {"type": "number", "required": True},
            "teacher_id": {"type": "number", "label": "Homeroom Teacher ID"},
        },
    },
    "subjects": {
        "table": "subjects",
        "title": "Subjects",
        "permission": "academic.manage",
        "search": ["code", "name", "department"],
        "list": ["code", "name", "department", "credit_hours", "created_at"],
        "fields": {
            "code": {"type": "text", "required": True},
            "name": {"type": "text", "required": True},
            "department": {"type": "text"},
            "credit_hours": {"type": "number", "required": True},
            "description": {"type": "textarea"},
        },
    },
    "curriculum": {
        "table": "curriculum",
        "title": "Curriculum",
        "permission": "academic.manage",
        "search": ["title", "grade_level", "term"],
        "list": ["title", "grade_level", "term", "status", "created_at"],
        "fields": {
            "subject_id": {"type": "number", "required": True, "label": "Subject ID"},
            "title": {"type": "text", "required": True},
            "grade_level": {"type": "text", "required": True},
            "term": {"type": "text", "required": True},
            "status": {"type": "select", "required": True, "options": ["Draft", "Approved", "Archived"]},
            "objectives": {"type": "textarea"},
        },
    },
    "attendance": {
        "table": "attendance",
        "title": "Attendance",
        "permission": "attendance.manage",
        "search": ["status", "remarks"],
        "list": ["attendance_date", "student_id", "class_id", "status", "created_at"],
        "fields": {
            "student_id": {"type": "number", "required": True, "label": "Student ID"},
            "class_id": {"type": "number", "required": True, "label": "Class ID"},
            "attendance_date": {"type": "date", "required": True},
            "status": {"type": "select", "required": True, "options": ["Present", "Absent", "Late", "Excused"]},
            "remarks": {"type": "textarea"},
        },
    },
    "timetable": {
        "table": "timetable_entries",
        "title": "Timetable",
        "permission": "academic.manage",
        "search": ["weekday", "room"],
        "list": ["weekday", "starts_at", "ends_at", "class_id", "subject_id", "room"],
        "fields": {
            "class_id": {"type": "number", "required": True, "label": "Class ID"},
            "subject_id": {"type": "number", "required": True, "label": "Subject ID"},
            "teacher_id": {"type": "number", "required": True, "label": "Teacher ID"},
            "weekday": {"type": "select", "required": True, "options": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]},
            "starts_at": {"type": "time", "required": True},
            "ends_at": {"type": "time", "required": True},
            "room": {"type": "text"},
        },
    },
    "assignments": {
        "table": "assignments",
        "title": "Assignments",
        "permission": "academic.manage",
        "search": ["title", "status"],
        "list": ["title", "class_id", "subject_id", "due_date", "status"],
        "fields": {
            "class_id": {"type": "number", "required": True, "label": "Class ID"},
            "subject_id": {"type": "number", "required": True, "label": "Subject ID"},
            "teacher_id": {"type": "number", "required": True, "label": "Teacher ID"},
            "title": {"type": "text", "required": True},
            "description": {"type": "textarea"},
            "due_date": {"type": "date", "required": True},
            "status": {"type": "select", "required": True, "options": ["Draft", "Published", "Closed"]},
        },
    },
    "examinations": {
        "table": "examinations",
        "title": "Examinations",
        "permission": "exams.manage",
        "search": ["name", "exam_type", "status"],
        "list": ["name", "exam_type", "starts_on", "ends_on", "status"],
        "fields": {
            "name": {"type": "text", "required": True},
            "exam_type": {"type": "select", "required": True, "options": ["CAT", "Midterm", "Final", "Mock", "Practical"]},
            "starts_on": {"type": "date", "required": True},
            "ends_on": {"type": "date", "required": True},
            "status": {"type": "select", "required": True, "options": ["Scheduled", "Running", "Completed", "Published"]},
        },
    },
    "results": {
        "table": "exam_results",
        "title": "Results",
        "permission": "exams.manage",
        "search": ["grade", "remarks"],
        "list": ["exam_id", "student_id", "subject_id", "score", "grade"],
        "fields": {
            "exam_id": {"type": "number", "required": True, "label": "Exam ID"},
            "student_id": {"type": "number", "required": True, "label": "Student ID"},
            "subject_id": {"type": "number", "required": True, "label": "Subject ID"},
            "score": {"type": "number", "required": True},
            "grade": {"type": "text", "required": True},
            "remarks": {"type": "textarea"},
        },
    },
    "finance": {
        "table": "invoices",
        "title": "Finance",
        "permission": "finance.manage",
        "search": ["invoice_no", "status"],
        "list": ["invoice_no", "student_id", "amount", "due_date", "status"],
        "fields": {
            "invoice_no": {"type": "text", "required": True},
            "student_id": {"type": "number", "required": True, "label": "Student ID"},
            "amount": {"type": "number", "required": True},
            "due_date": {"type": "date", "required": True},
            "status": {"type": "select", "required": True, "options": ["Draft", "Issued", "Partially Paid", "Paid", "Overdue", "Cancelled"]},
            "notes": {"type": "textarea"},
        },
    },
    "payroll": {
        "table": "payroll",
        "title": "Payroll",
        "permission": "payroll.manage",
        "search": ["pay_period", "status"],
        "list": ["employee_id", "pay_period", "gross_pay", "net_pay", "status"],
        "fields": {
            "employee_id": {"type": "number", "required": True, "label": "Employee ID"},
            "pay_period": {"type": "text", "required": True},
            "gross_pay": {"type": "number", "required": True},
            "deductions": {"type": "number", "required": True},
            "net_pay": {"type": "number", "required": True},
            "status": {"type": "select", "required": True, "options": ["Draft", "Approved", "Paid"]},
        },
    },
    "hr": {
        "table": "employees",
        "title": "HR",
        "permission": "hr.manage",
        "search": ["employee_no", "first_name", "last_name", "department", "position"],
        "list": ["employee_no", "first_name", "last_name", "department", "position", "status"],
        "fields": {
            "employee_no": {"type": "text", "required": True},
            "first_name": {"type": "text", "required": True},
            "last_name": {"type": "text", "required": True},
            "department": {"type": "text", "required": True},
            "position": {"type": "text", "required": True},
            "email": {"type": "email"},
            "phone": {"type": "tel"},
            "hire_date": {"type": "date"},
            "status": {"type": "select", "required": True, "options": ["Active", "On Leave", "Inactive", "Exited"]},
        },
    },
    "library": {
        "table": "library_books",
        "title": "Library",
        "permission": "library.manage",
        "search": ["isbn", "title", "author", "category"],
        "list": ["isbn", "title", "author", "category", "available_copies"],
        "fields": {
            "isbn": {"type": "text", "required": True},
            "title": {"type": "text", "required": True},
            "author": {"type": "text", "required": True},
            "category": {"type": "text"},
            "total_copies": {"type": "number", "required": True},
            "available_copies": {"type": "number", "required": True},
            "shelf_location": {"type": "text"},
        },
    },
    "hostel": {
        "table": "hostel_rooms",
        "title": "Hostel",
        "permission": "hostel.manage",
        "search": ["hostel_name", "room_no", "room_type"],
        "list": ["hostel_name", "room_no", "room_type", "capacity", "occupied"],
        "fields": {
            "hostel_name": {"type": "text", "required": True},
            "room_no": {"type": "text", "required": True},
            "room_type": {"type": "select", "required": True, "options": ["Single", "Double", "Dormitory"]},
            "capacity": {"type": "number", "required": True},
            "occupied": {"type": "number", "required": True},
            "status": {"type": "select", "required": True, "options": ["Available", "Full", "Maintenance"]},
        },
    },
    "transport": {
        "table": "transport_routes",
        "title": "Transport",
        "permission": "transport.manage",
        "search": ["route_name", "vehicle_no", "driver_name"],
        "list": ["route_name", "vehicle_no", "driver_name", "monthly_fee", "status"],
        "fields": {
            "route_name": {"type": "text", "required": True},
            "vehicle_no": {"type": "text", "required": True},
            "driver_name": {"type": "text", "required": True},
            "driver_phone": {"type": "tel"},
            "monthly_fee": {"type": "number", "required": True},
            "status": {"type": "select", "required": True, "options": ["Active", "Maintenance", "Inactive"]},
        },
    },
    "communication": {
        "table": "messages",
        "title": "Communication",
        "permission": "communication.manage",
        "search": ["subject", "channel", "audience"],
        "list": ["subject", "channel", "audience", "status", "created_at"],
        "fields": {
            "subject": {"type": "text", "required": True},
            "body": {"type": "textarea", "required": True},
            "channel": {"type": "select", "required": True, "options": ["Email", "SMS", "Portal", "Push"]},
            "audience": {"type": "select", "required": True, "options": ["All", "Students", "Parents", "Teachers", "Staff"]},
            "status": {"type": "select", "required": True, "options": ["Draft", "Scheduled", "Sent"]},
        },
    },
    "announcements": {
        "table": "school_announcements",
        "title": "Announcements",
        "permission": "communication.manage",
        "search": ["title", "category", "audience", "status"],
        "list": ["title", "category", "audience", "publish_on", "status"],
        "fields": {
            "title": {"type": "text", "required": True},
            "body": {"type": "textarea", "required": True},
            "category": {"type": "select", "required": True, "options": ["General", "Event", "Academic", "Finance", "Emergency", "Sports"]},
            "audience": {"type": "select", "required": True, "options": ["All", "Students", "Parents", "Teachers", "Staff"]},
            "publish_on": {"type": "date", "required": True},
            "status": {"type": "select", "required": True, "options": ["Draft", "Scheduled", "Published", "Archived"]},
        },
    },
    "sms-reports": {
        "table": "sms_reports",
        "title": "SMS Reports",
        "permission": "communication.manage",
        "search": ["provider", "campaign_name", "status"],
        "list": ["campaign_name", "provider", "recipient_count", "sent_count", "failed_count", "status"],
        "fields": {
            "campaign_name": {"type": "text", "required": True},
            "provider": {"type": "text", "required": True},
            "recipient_count": {"type": "number", "required": True},
            "sent_count": {"type": "number", "required": True},
            "failed_count": {"type": "number", "required": True},
            "credits_used": {"type": "number", "required": True},
            "status": {"type": "select", "required": True, "options": ["Queued", "Sent", "Partially Failed", "Failed"]},
            "sent_at": {"type": "date"},
        },
    },
    "canteen": {
        "table": "canteen_orders",
        "title": "Canteen",
        "permission": "finance.manage",
        "search": ["order_no", "customer_name", "item_name", "payment_status"],
        "list": ["order_no", "customer_name", "item_name", "quantity", "total_amount", "payment_status"],
        "fields": {
            "order_no": {"type": "text", "required": True},
            "customer_name": {"type": "text", "required": True},
            "customer_type": {"type": "select", "required": True, "options": ["Student", "Staff", "Guest"]},
            "item_name": {"type": "text", "required": True},
            "quantity": {"type": "number", "required": True},
            "unit_price": {"type": "number", "required": True},
            "total_amount": {"type": "number", "required": True},
            "payment_status": {"type": "select", "required": True, "options": ["Pending", "Paid", "Refunded"]},
        },
    },
    "receipts": {
        "table": "fee_receipts",
        "title": "Fee Receipts",
        "permission": "finance.manage",
        "search": ["receipt_no", "student_name", "payment_method"],
        "list": ["receipt_no", "student_name", "amount_paid", "payment_method", "issued_on"],
        "fields": {
            "receipt_no": {"type": "text", "required": True},
            "student_id": {"type": "number", "label": "Student ID"},
            "student_name": {"type": "text", "required": True},
            "amount_paid": {"type": "number", "required": True},
            "payment_method": {"type": "select", "required": True, "options": ["Cash", "Bank", "Mobile Money", "Card", "Cheque"]},
            "issued_on": {"type": "date", "required": True},
            "notes": {"type": "textarea"},
        },
    },
    "expenses": {
        "table": "expenses",
        "title": "Expenses",
        "permission": "finance.manage",
        "search": ["expense_no", "category", "vendor", "status"],
        "list": ["expense_no", "category", "vendor", "amount", "expense_date", "status"],
        "fields": {
            "expense_no": {"type": "text", "required": True},
            "category": {"type": "text", "required": True},
            "vendor": {"type": "text"},
            "amount": {"type": "number", "required": True},
            "expense_date": {"type": "date", "required": True},
            "status": {"type": "select", "required": True, "options": ["Draft", "Submitted", "Approved", "Paid", "Rejected"]},
            "notes": {"type": "textarea"},
        },
    },
    "scholarships": {
        "table": "scholarships",
        "title": "Scholarships",
        "permission": "finance.manage",
        "search": ["award_name", "student_name", "status"],
        "list": ["award_name", "student_name", "amount", "academic_year", "status"],
        "fields": {
            "award_name": {"type": "text", "required": True},
            "student_id": {"type": "number", "label": "Student ID"},
            "student_name": {"type": "text", "required": True},
            "amount": {"type": "number", "required": True},
            "academic_year": {"type": "text", "required": True},
            "status": {"type": "select", "required": True, "options": ["Applied", "Approved", "Awarded", "Revoked"]},
            "notes": {"type": "textarea"},
        },
    },
    "school-profile": {
        "table": "school_profiles",
        "title": "School Profile",
        "permission": "settings.manage",
        "search": ["school_name", "institution_type", "school_email", "city"],
        "list": ["school_name", "institution_type", "school_email", "phone_number", "city", "status"],
        "fields": {
            "school_name": {"type": "text", "required": True},
            "institution_type": {"type": "select", "required": True, "options": ["Secondary School", "University"]},
            "school_email": {"type": "email", "required": True},
            "phone_number": {"type": "tel"},
            "address": {"type": "textarea"},
            "city": {"type": "text"},
            "country": {"type": "text"},
            "brand_color": {"type": "text"},
            "status": {"type": "select", "required": True, "options": ["Active", "Inactive"]},
        },
    },
    "user-management": {
        "table": "users",
        "title": "User Management",
        "permission": "settings.manage",
        "search": ["full_name", "email", "institution_type", "portal_key", "status"],
        "list": ["full_name", "email", "institution_type", "portal_key", "status"],
        "fields": {
            "role_id": {"type": "number", "required": True, "label": "Role ID"},
            "full_name": {"type": "text", "required": True},
            "email": {"type": "email", "required": True},
            "password": {"type": "password", "required": True, "label": "Temporary Password", "virtual": True},
            "institution_type": {"type": "select", "required": True, "options": ["global", "secondary", "university"]},
            "portal_key": {"type": "text", "required": True},
            "status": {"type": "select", "required": True, "options": ["Active", "Suspended", "Disabled"]},
        },
    },
    "permissions": {
        "table": "permissions",
        "title": "Permissions",
        "permission": "settings.manage",
        "search": ["permission_key", "name"],
        "list": ["permission_key", "name", "created_at"],
        "fields": {
            "permission_key": {"type": "text", "required": True},
            "name": {"type": "text", "required": True},
        },
    },
    "audit-logs": {
        "table": "audit_logs",
        "title": "Audit Logs",
        "permission": "settings.manage",
        "search": ["action", "entity", "ip_address"],
        "list": ["user_id", "action", "entity", "entity_id", "created_at"],
        "fields": {
            "user_id": {"type": "number", "label": "User ID"},
            "action": {"type": "text", "required": True},
            "entity": {"type": "text", "required": True},
            "entity_id": {"type": "number", "label": "Entity ID"},
            "ip_address": {"type": "text"},
            "metadata_json": {"type": "textarea"},
        },
    },
    "reports": {
        "table": "saved_reports",
        "title": "Reports",
        "permission": "reports.view",
        "search": ["name", "report_type"],
        "list": ["name", "report_type", "created_by", "created_at"],
        "fields": {
            "name": {"type": "text", "required": True},
            "report_type": {"type": "select", "required": True, "options": ["Attendance", "Student", "Teacher", "Finance", "Library", "Hostel", "Transport", "Exam"]},
            "parameters_json": {"type": "textarea"},
            "created_by": {"type": "number", "label": "Created By User ID"},
        },
    },
    "settings": {
        "table": "school_settings",
        "title": "Settings",
        "permission": "settings.manage",
        "search": ["setting_key", "setting_value"],
        "list": ["setting_key", "setting_value", "updated_at"],
        "fields": {
            "setting_key": {"type": "text", "required": True},
            "setting_value": {"type": "textarea", "required": True},
        },
    },
}


INSTITUTION_SCOPED_MODULES = {
    "admissions",
    "students",
    "parents",
    "teachers",
    "academic",
    "classes",
    "subjects",
    "curriculum",
    "attendance",
    "timetable",
    "assignments",
    "examinations",
    "results",
    "finance",
    "payroll",
    "hr",
    "library",
    "hostel",
    "transport",
    "communication",
    "announcements",
    "sms-reports",
    "canteen",
    "receipts",
    "expenses",
    "scholarships",
    "reports",
    "user-management",
    "settings",
    "audit-logs",
}

for module_key in INSTITUTION_SCOPED_MODULES:
    if module_key in MODULES:
        MODULES[module_key]["institution_scoped"] = True


NAVIGATION = [
    ("dashboard", "Dashboard", "dashboard.view"),
    ("admissions", "Admissions", "admissions.manage"),
    ("students", "Students", "students.manage"),
    ("parents", "Parents", "parents.manage"),
    ("teachers", "Teachers", "teachers.manage"),
    ("academic", "Academic", "academic.manage"),
    ("classes", "Class Management", "academic.manage"),
    ("subjects", "Subjects", "academic.manage"),
    ("curriculum", "Curriculum", "academic.manage"),
    ("attendance", "Attendance", "attendance.manage"),
    ("timetable", "Timetable", "academic.manage"),
    ("assignments", "Assignments", "academic.manage"),
    ("examinations", "Examinations", "exams.manage"),
    ("results", "Results", "exams.manage"),
    ("finance", "Finance", "finance.manage"),
    ("payroll", "Payroll", "payroll.manage"),
    ("hr", "HR", "hr.manage"),
    ("library", "Library", "library.manage"),
    ("hostel", "Hostel", "hostel.manage"),
    ("transport", "Transport", "transport.manage"),
    ("communication", "Communication", "communication.manage"),
    ("announcements", "Announcements", "communication.manage"),
    ("sms-reports", "SMS Reports", "communication.manage"),
    ("canteen", "Canteen", "finance.manage"),
    ("receipts", "Receipts", "finance.manage"),
    ("expenses", "Expenses", "finance.manage"),
    ("scholarships", "Scholarships", "finance.manage"),
    ("reports", "Reports", "reports.view"),
    ("user-management", "User Management", "settings.manage"),
    ("settings", "Settings", "settings.manage"),
    ("audit-logs", "Audit Logs", "settings.manage"),
]
